# Generated by Django 5.0.7 on 2024-08-04 01:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="descripiton",
            new_name="description",
        ),
    ]
